# USING TENSORFLOW


In [1]:
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
import keras

In [2]:
### observation 

In [3]:
observations = 1000

xs = np.random.uniform(low=-10, high=10, size=(observations,1))
zs = np.random.uniform(-10, 10, (observations,1))

generated_inputs = np.column_stack((xs,zs))

noise = np.random.uniform(-1, 1, (observations,1))

generated_targets = 2*xs - 3*zs + 5 + noise

np.savez('TF_intro', inputs=generated_inputs, targets=generated_targets)


In [4]:
training_data = np.load('TF_intro.npz')

In [5]:
input_size = 2
output_size =1 
#when we use tensorflow wemust actually build the model 


To build a machine learning model, we typically follow four steps:

acquire and preprocess data
create a model architecture
define an objective function to measure performance
choose an optimization algorithm to train the model. We will be implementing all four steps using TensorFlow.
for 
Data: We will use TensorFlow's tf.data module to load and preprocess our data.
Model: We will use TensorFlow's tf.keras.Sequential API to define our model architecture.
Objective function: We will use TensorFlow's built-in loss functions and metrics, such as tf.keras.losses.BinaryCrossentropy and tf.keras.metrics.BinaryAccuracy.
Optimization algorithm: We will use TensorFlow's built-in optimizers, such as tf.keras.optimizers.Adam, to optimize our model during training.
    IN OUR EXAMPLE WE WILL USE 
    SGD stands for Stochastic Gradient Descent and it's a popular optimization algorithm used in deep learning to minimize the loss function during model training.
In TensorFlow, we can use the SGD optimizer by creating an instance of the tf.keras.optimizers.SGD class and passing the desired learning rate as a parameter.

In [6]:
import tensorflow.keras as keras

# Declare a variable where we will store the input size of our model
# It should be equal to the number of variables you have
input_size = 2
# Declare the output size of the model
# It should be equal to the number of outputs you've got (for regressions that's usually 1)
output_size = 1

# Outline the model
# We lay out the model in 'Sequential'
# Note that there are no calculations involved - we are just describing our network
model = tf.keras.Sequential([
                            # Each 'layer' is listed here
                            # The method 'Dense' indicates, our mathematical operation to be (xw + b)
                            tf.keras.layers.Dense(output_size,
                                                 # there are extra arguments you can include to customize your model
                                                 # in our case we are just trying to create a solution that is 
                                                 # as close as possible to our NumPy model
                                                 kernel_initializer=tf.random_uniform_initializer(minval=-0.1, maxval=0.1),
                                                 bias_initializer=tf.random_uniform_initializer(minval=-0.1, maxval=0.1)
                                                 )
                            ])

# We can also define a custom optimizer, where we can specify the learning rate
custom_optimizer = tf.keras.optimizers.SGD(learning_rate=0.02)
# Note that sometimes you may also need a custom loss function 
# That's much harder to implement and won't be covered in this course though

# 'compile' is the place where you select and indicate the optimizers and the loss
model.compile(optimizer=custom_optimizer, loss='mean_squared_error')

# finally we fit the model, indicating the inputs and targets
# if they are not otherwise specified the number of epochs will be 1 (a single epoch of training), 
# so the number of epochs is 'kind of' mandatory, too
# we can play around with verbose; we prefer verbose=2
model.fit(training_data['inputs'], training_data['targets'], epochs=100, verbose=2)

Epoch 1/100
32/32 - 1s - loss: 25.9400 - 1s/epoch - 38ms/step
Epoch 2/100
32/32 - 0s - loss: 1.2719 - 79ms/epoch - 2ms/step
Epoch 3/100
32/32 - 0s - loss: 0.4640 - 83ms/epoch - 3ms/step
Epoch 4/100
32/32 - 0s - loss: 0.4347 - 89ms/epoch - 3ms/step
Epoch 5/100
32/32 - 0s - loss: 0.4083 - 92ms/epoch - 3ms/step
Epoch 6/100
32/32 - 0s - loss: 0.3697 - 102ms/epoch - 3ms/step
Epoch 7/100
32/32 - 0s - loss: 0.3938 - 117ms/epoch - 4ms/step
Epoch 8/100
32/32 - 0s - loss: 0.3914 - 88ms/epoch - 3ms/step
Epoch 9/100
32/32 - 0s - loss: 0.3783 - 104ms/epoch - 3ms/step
Epoch 10/100
32/32 - 0s - loss: 0.4171 - 98ms/epoch - 3ms/step
Epoch 11/100
32/32 - 0s - loss: 0.4321 - 98ms/epoch - 3ms/step
Epoch 12/100
32/32 - 0s - loss: 0.4248 - 105ms/epoch - 3ms/step
Epoch 13/100
32/32 - 0s - loss: 0.3927 - 104ms/epoch - 3ms/step
Epoch 14/100
32/32 - 0s - loss: 0.4009 - 112ms/epoch - 4ms/step
Epoch 15/100
32/32 - 0s - loss: 0.4333 - 95ms/epoch - 3ms/step
Epoch 16/100
32/32 - 0s - loss: 0.4228 - 90ms/epoch - 3ms/

tf.keras.Sequential is a class in TensorFlow's Keras API that allows you to create a neural network model as a sequence of layers. The layers are added to the model in the order they are passed to the Sequential constructor, and each layer is connected to the previous layer.

tf.keras.layers.Dense is a fully connected layer in a neural network. It implements the operation: output = activation(dot(input, kernel) + bias) where activation is the element-wise activation function passed as the activation argument, kernel is a weights matrix created by the layer, and bias is a bias vector created by the layer (only applicable if use_bias is True).from numpy before we used the code (output= np.dot(input,weights) + biase, NOW WE USE TF.KERAS.DENSE 

model.compile is a method in TensorFlow that configures the model for training. It takes several arguments, including the optimizer, loss function, and evaluation metric(s).

model.fit is a method in TensorFlow that trains the model on a given dataset. It takes several arguments, including the training data, validation data (optional), batch size, number of epochs, and more.

In [7]:
# Extracting the weights and biases is achieved quite easily
model.layers[0].get_weights()

[array([[ 1.9868708],
        [-3.0834076]], dtype=float32),
 array([4.9973536], dtype=float32)]

In [8]:
# We can save the weights and biases in separate variables for easier examination
# Note that there can be hundreds or thousands of them!
weights = model.layers[0].get_weights()[0]
weights

array([[ 1.9868708],
       [-3.0834076]], dtype=float32)

In [9]:
# We can save the weights and biases in separate variables for easier examination
# Note that there can be hundreds or thousands of them!
bias = model.layers[0].get_weights()[1]
bias

array([4.9973536], dtype=float32)

# Extract the outputs (make predictions)
Once more, this is not an essential step, however, we usually want to be able to make predictions.

In [10]:
# We can predict new values in order to actually make use of the model
# Sometimes it is useful to round the values to be able to read the output
# Usually we use this method on NEW DATA, rather than our original training data
model.predict_on_batch(training_data['inputs']).round(1)

array([[ -9.3],
       [-15.2],
       [ 24.4],
       [-22.3],
       [ 34.7],
       [ -0.6],
       [-35. ],
       [ 34.7],
       [-22.2],
       [ -1.4],
       [ 21.8],
       [ 27.8],
       [-27.9],
       [-10.6],
       [ 39.4],
       [-26. ],
       [ -6.5],
       [ 21.5],
       [  9.7],
       [-12.3],
       [-18.7],
       [ -7.5],
       [  4.9],
       [ 15.8],
       [  0.5],
       [ 50. ],
       [ 27.4],
       [ 14.5],
       [ 14.2],
       [ -0.6],
       [ 19.2],
       [ 10.2],
       [-10.5],
       [ 49.5],
       [ 39.5],
       [ 39.2],
       [  6.9],
       [ 23.9],
       [ 22.9],
       [  3.8],
       [  2.9],
       [ 12.9],
       [ 11.1],
       [ 17. ],
       [ 11.4],
       [ 18.6],
       [-21.9],
       [-20.4],
       [  9.1],
       [ 38.7],
       [-20.6],
       [ 11.1],
       [ 19.6],
       [ 22.4],
       [  3.5],
       [  2.3],
       [ 15.7],
       [  9.8],
       [ 24.1],
       [ 15.1],
       [ 39.2],
       [-25.8],
       [

In [11]:
# If we display our targets (actual observed values), we can manually compare the outputs and the targets
training_data['targets'].round(1)

array([[-10.3],
       [-14.6],
       [ 24.3],
       [-20.8],
       [ 35.1],
       [ -0.8],
       [-33.8],
       [ 34.1],
       [-21.3],
       [ -2.6],
       [ 21.8],
       [ 28.1],
       [-28.6],
       [ -9.9],
       [ 39.5],
       [-24.7],
       [ -5.4],
       [ 22.3],
       [  9.3],
       [-12.8],
       [-17.4],
       [ -8.1],
       [  4.3],
       [ 16.1],
       [  0.6],
       [ 48.7],
       [ 27.8],
       [ 13.7],
       [ 15. ],
       [ -0.1],
       [ 17.7],
       [ 10.8],
       [-10.8],
       [ 49.5],
       [ 39.3],
       [ 39. ],
       [  5.9],
       [ 23.8],
       [ 21.6],
       [  5. ],
       [  3.7],
       [ 13.3],
       [ 10.3],
       [ 16.3],
       [ 12.2],
       [ 17.3],
       [-20.7],
       [-20.8],
       [  8.1],
       [ 37.5],
       [-19.7],
       [ 10.3],
       [ 20.3],
       [ 23.1],
       [  3.6],
       [  3.4],
       [ 15.3],
       [  8.3],
       [ 24.4],
       [ 15.6],
       [ 39. ],
       [-25. ],
       [

# Plotting the data

In [4]:

import matplotlib.pyplot as plt
import numpy as np 
# The model is optimized, so the outputs are calculated based on the last form of the model
model = tf.keras.Sequential([
                            # Each 'layer' is listed here
                            # The method 'Dense' indicates, our mathematical operation to be (xw + b)
                            tf.keras.layers.Dense(output_size,
                                                 # there are extra arguments you can include to customize your model
                                                 # in our case we are just trying to create a solution that is 
                                                 # as close as possible to our NumPy model
                                                 kernel_initializer=tf.random_uniform_initializer(minval=-0.1, maxval=0.1),
                                                 bias_initializer=tf.random_uniform_initializer(minval=-0.1, maxval=0.1)
                                                 )
                            ])

# We have to np.squeeze the arrays in order to fit them to what the plot function expects.
# Doesn't change anything as we cut dimensions of size 1 - just a technicality.
plt.plot(np.squeeze(model.predict_on_batch(training_data['inputs'])), np.squeeze(training_data['targets']))
plt.xlabel('outputs')
plt.ylabel('targets')
plt.show()

# Voila - what you see should be exactly the same as in the previous notebook!
# You probably don't see the point of TensorFlow now - it took us the same number of lines of code
# to achieve this simple result. However, once we go deeper in the next chapter,
# TensorFlow will save us hundreds of lines of code.


NameError: name 'tf' is not defined